### ISSUE TITLE
[Bug] Failure to display Widgets pointing to Elements without art

### ISSUE THREAD

**Issue by Zhiro90** [drinfernoo/plugin.program.autowidget#92]
**Describe the bug**
A displayed widget group will behave normally unless it has to display elements with art completely set up. Instead, the widget fails to load and an error notification pops up

**To Reproduce**
1.  Add "Genres" or "Directors" to test widget group
2. Add test widget group to skin home
3. Scroll to it.

**To Reproduce (Alt)**
1.  Add "Genres" or "Directors" to test widget group
2. Open Autowidget Addon
3. Navigate to test widget group
4. Open Test Widget Group
5. Attempt to open an element

**Expected behavior**
Element Icons would display

**Details:**
  - Kodi Leia
  - Auramod
  - Windows 7 PC

**Additional context**
Log Excerpt:

2021-06-25 08:31:17.599 T:8184  NOTICE: plugin.program.autowidget: [ group: genres3-1624627651.39 ][ mode: group ]
2021-06-25 08:31:17.702 T:8184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'art'
                                            Traceback (most recent call last):
                                              File "C:\Z\Apps\Program Files\Kodi\portable_data\addons\plugin.program.autowidget\main.py", line 13, in <module>
                                                router.dispatch(_plugin, _handle, _params)
                                              File "C:\Z\Apps\Program Files\Kodi\portable_data\addons\plugin.program.autowidget\resources\lib\common\router.py", line 63, in dispatch
                                                is_dir, category = menu.group_menu(group)
                                              File "C:\Z\Apps\Program Files\Kodi\portable_data\addons\plugin.program.autowidget\resources\lib\menu.py", line 130, in group_menu
                                                art=path_def["file"]["art"] or art,
                                            KeyError: 'art'
                                            -->End of Python script error report<--
2021-06-25 08:31:18.070 T:4804   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.autowidget/?group=genres3-1624627651.39&mode=group&refresh&reload
2021-06-25 08:31:18.073 T:14228   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.autowidget/?group=genres3-1624627651.39&mode=group&refresh&reload) failed

**Comment by drinfernoo** [comment]
What exactly are you adding into your groups? Are these library menus? like the "Genres" *item* from your library? And then you're making a widget if the actual group? If so, I'd recommend using these as a Shortcut Group. The issue may still arise, but Widget Groups should be used for *content*, whereas Shortcut Groups are for *shortcuts* to sections, basically.

**Comment by Zhiro90** [comment]
Thanks. I'll try your suggestions later

**Comment by Zhiro90** [comment]
So I've tried out a bunch of stuff. These are my findings:

[This issue seems to be the same as mine](https://github.com/drinfernoo/plugin.program.autowidget/issues/51) 

My goal was to have a widget group that would cycle between showing my available genres, studios and actors. That's exactly what was shown in [the introduction video (from 1:30-2:00, showing the result at 3:55)](https://www.youtube.com/watch?v=lA67gDeaa98).

In the linked issue, it was mentioned that that guide was outdated. So what I'm asking is: Are my desired groups still possible under the newest version? (Using 3.2 IIRC)

Tried every option of the procedure and none of them worked. Widgets with genres, studios and actors just fail to load. Movies and shows load correctly.

Here are captures  of what I did (shortcuts options didn't work either)

[CYCLING WIDGET](https://youtu.be/xNtf7kycPvg)
[EXPLODE AS WIDGET GROUP](https://youtu.be/hassN-tu4ys)

**Comment by drinfernoo** [comment]
For this, use a cycling widget from a widget group.

**Comment by Zhiro90** [comment]
Isn't that the one I linked in the previous post? [posted as WIDGET, now named CYCLYNG WIDGET](https://youtu.be/xNtf7kycPvg) <- Those are youtube links. Maybe I'm missing something?

**Comment by drinfernoo** [comment]
@Zhiro90 Ah, you're right. That does look right. Is the error you're getting in that video the same as the one you attached in the issue?

**Comment by Zhiro90** [comment]
Yes its the same log. 

I feel its related to the other issue i linked. And that user didnt actually solve it, they just desisted from using those.

**Comment by drinfernoo** [comment]
Can you try out `3.2.1` to see if it's fixed now? It worked for me to simply upgrade and point a widget at an already existing group.

**Comment by Zhiro90** [comment]
It's  loading properly now! I should ping the other user si they can try again.

Thank you so much.  I really appreciate it.

**Comment by Zhiro90** [comment]
Sorry for reopening and taking a while, I was recording.

Just a lil head's up, genres and studio icons aren't showing, even when changing the widget style, [here's a capture.](https://youtu.be/QUtHpoD9OwU)

The same folder view shows up in the widget itself [here's a screencap](https://i.imgur.com/2QPYMAM.png)

Artist do show up correctly

**Comment by drinfernoo** [comment]
Interesting... I think that those genre icons are actually put there by the skin, and aren't something that is attached to the item. I'll have to look into it.

**Comment by Zhiro90** [comment]
Those come form downloadable icon packs (through the kodi repo itself), I'm still not quite sure how they work as I was just starting to set them up when I installed autowidget. The issue seems to be that the widget sends to a folder view, very distinct to the usual genres view

**Comment by drinfernoo** [comment]
I'll need to see how your groups are set up, I'm afraid. The easiest way to do this is with an AutoWidget backup (from settings).

**Comment by Zhiro90** [comment]
[BACKUP.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/6815540/BACKUP.zip)

{
    "paths": [
        {
            "target": "widget", 
            "color": "white", 
            "label": "Genres", 
            "content": "", 
            "window": "videos", 
            "version": "3.2.3", 
            "file": {
                "filetype": "directory", 
                "art": {
                    "icon": "DefaultGenre.png"
                }, 
                "votes": "0", 
                "file": "videodb://movies/genres/"
            }, 
            "id": "genres-1626260005.99"
        }, 
        {
            "target": "widget", 
            "color": "white", 
            "label": "Actors", 
            "content": "", 
            "window": "videos", 
            "version": "3.2.3", 
            "file": {
                "filetype": "directory", 
                "art": {
                    "icon": "DefaultActor.png"
                }, 
                "votes": "0", 
                "file": "videodb://movies/actors/"
            }, 
            "id": "actors-1626260023.69"
        }, 
        {
            "target": "widget", 
            "color": "white", 
            "label": "Studios", 
            "content": "", 
            "window": "videos", 
            "version": "3.2.3", 
            "file": {
                "filetype": "directory", 
                "art": {
                    "icon": "DefaultStudios.png"
                }, 
                "votes": "0", 
                "file": "videodb://movies/studios/"
            }, 
            "id": "studios-1626260039.62"
        }, 
        {
            "target": "widget", 
            "color": "white", 
            "label": "Directors", 
            "content": "", 
            "window": "videos", 
            "version": "3.2.3", 
            "file": {
                "filetype": "directory", 
                "art": {
                    "icon": "DefaultDirector.png"
                }, 
                "votes": "0", 
                "file": "videodb://movies/directors/"
            }, 
            "id": "directors-1626260055.44"
        }
    ], 
    "art": {
        "fanart": "special://home/addons\\plugin.program.autowidget\\resources\\media\\fanart\\folder-sync.png", 
        "poster": "special://home/addons\\plugin.program.autowidget\\resources\\media\\poster\\folder-sync.png", 
        "banner": "special://home/addons\\plugin.program.autowidget\\resources\\media\\banner\\folder-sync.png", 
        "thumb": "special://home/addons\\plugin.program.autowidget\\resources\\media\\icon\\folder-sync.png", 
        "icon": "special://home/addons\\plugin.program.autowidget\\resources\\media\\icon\\folder-sync.png"
    }, 
    "label": "Categories", 
    "version": "3.2.0", 
    "type": "widget", 
    "id": "test-1624708355.98"
}

**Comment by drinfernoo** [comment]
Ok, so I've figured out why it's *not* working. Most skins look at either **a)** the "dbtype" of the item, or **b)** the "content" of the menu they're shown in, to determine if the items are a genre, studio, country, etc..., and set the icon accordingly, pulling it directly from one of the resource add-ons you mentioned previously. The icons *aren't* attached directly to the item.

Now, unfortunately, I don't have a super reliable way of setting the "dbtype" on individual items, and Kodi doesn't allow add-ons to set the "content" of a widget container, as far as I can find.

My "workaround" for this is going to be to simply set those icons from the resource pack myself, but it's going to take a little bit of work. I have it working (in theory), but would like to implement a system in which the user can choose from any of the resource packs available on the repo, which should give quite a bit more flexibility with which icons can *actually be used*, since not all skins use the same ones by default.

Stay tuned for more 👍

**Comment by drinfernoo** [comment]
Yep, so this will be supported in 3.3.0 🎉 I've implemented a feature in settings where you can install various icon packs, and whichever you choose will be used for the widgets you've been talking about.

Currently this only officially supports library widgets, and the setting is AutoWidget-global, so you can't change icon pack per-widget. If people want some other stuff, let me know :+1:
